---
title: "Plasticity/Switching 2"
author: "Gabe Zuckerman"
date: "6/23/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(data.table)
library(tidyverse)
library(cluster) 
library(factoextra)
library(ClusterR)
library(fpc)
library(ggalluvial)
library(knitr)
library(kableExtra)
library(usdm)
library(furrr)
library(caret)
library(lubridate)
library(Hmisc)
library(vegan)



setwd("C:/Users/MiddletonLab/Desktop/Gabe/Box Sync/Elk/Plasticity1/")


distances <- fread("movementData/distanceChanges.csv")

timing <- fread("../Switching3/timingData/finalTiming.csv", na.strings = "")

```

Single year movements

```{r fixing residents, echo=F}
#change figures to only include elk in final dataset

distances$elk <- map_chr(distances$id, ~strsplit(.x, "_")[[1]][1])

getIndYears <- function(row) {
  test <- distances[row,]
  
  #extracting info from each row
  years <- strsplit(strsplit(test$id[1], "_")[[1]], "-")[[2]]
  dists <- c(test$sp1dist[1], test$sp2dist[1])
  elevs <- c(test$sp1elev[1], test$sp2elev[1])
  elk <- c(test$elk[1], test$elk[1])
  
  return(data.table(elk, years, dists, elevs, herd = test$herd[1]))
}

allIndYears <- map_dfr(1:nrow(distances), getIndYears) %>% distinct(elk, years, .keep_all = T) %>%
  mutate(absElev = abs(elevs)) %>% mutate(elkYear = paste(elk, years, sep = "_"))

#if an elk had no timing in a year, then changing is distance to 0
residents <- allIndYears %>% filter(elkYear %in%  filter(timing, reclass == "resident")$elkYear) %>%
  mutate(dists = 0, elevs = 0, absElev = 0, class = "R")
nonRes <- allIndYears %>% filter(elkYear %nin% residents$elkYear) %>% mutate(class = NA)

allIndYears <- rbind(residents, nonRes)

#residents are now at (0,0)
ggplot(allIndYears) + geom_point(aes(dists, absElev), alpha = .5) + ylab("Abosulte elevation change") +
  xlab("Geographic distance") + theme_bw() + ggtitle("Figure 1.")

```


```{r classify, echo=FALSE}
#change figures to only include elk in final dataset


forCluster <- allIndYears %>% filter(is.na(class)) %>%
  dplyr::select(dists, absElev) %>% mutate(dists = scale(dists, center = T),
                                                  absElev = scale(absElev, center = T))

#kmeans with 3
set.seed(1)

k <- kmeans(forCluster, centers = 3, nstart = 25)
nonRes <- allIndYears %>% filter(is.na(class)) %>% mutate(class = k$cluster) %>%
  merge(data.table(class = 1:3, strategy = c("LDM", "EM", "SDM"))) %>% dplyr::select(-class) %>%
  rename(class = strategy)


allIndYears <- rbind(allIndYears %>% filter(class == "R"), nonRes)

library(extrafont)
loadfonts(device = "win")

ggplot(allIndYears) + geom_point(aes(dists, absElev, color = class), alpha = .3) +
  ylab("Abosulte elevation change (m)") +   xlab("Geographic distance (m)") + 
  geom_text(x=25000, y=1100, label="Elev. M (21.9%)", color = "#1b9e77", size = 9, family = "Century Gothic") +
  geom_text(x=25000, y=400, label="SDM (53.7%)", color = "#e7298a", size = 9, family = "Century Gothic") +
  geom_text(x = 75000, y = 1000, label = "LDM (19.6%)", color = "#d95f02", size = 9, family = "Century Gothic") + 
  geom_text(x = 18000, y = 0, label = "R (4.8%)", color = "#7570b3", size = 9, family = "Century Gothic") +
  theme_bw() + theme(legend.position = "none", text=element_text(size=16, family = "Century Gothic"), 
                     plot.title = element_text(hjust = 0.5)) + 
  scale_color_manual(values = c("#1b9e77", "#d95f02", "#7570b3", "#e7298a")) + ggtitle("Migratory Portfolio")
  


```

```{r first day DNHM, echo = F, eval = F}
library(plotly)

set.seed(1)
resX <- rnorm(200, mean = 3000, sd = 5000)
resY <- rnorm(200, mean = 0, sd = 100)

resF1 <- data.table(dists = resX, absElev = resY, class  = "R", f = 1)

sdmX <- runif(100, min = 100, max = 100)
sdmY <- runif(100, min = 0, max = 0)

sdmF1 <- data.table(dists = sdmX, absElev = sdmY, class = "SDM", f = 1)

emX <- runif(100, min = 100000, max = 100000)
emY <- runif(100, min = 1525, max = 1575)

emF1 <- data.table(dists = emX, absElev = emY, class = "EM", f = 1)

ldmX <- rnorm(490, mean = 100000, sd = 5000)
ldmY <- rnorm(490, mean = 1500, sd = 200)

ldmF1 <- data.table(dists = ldmX, absElev = ldmY, class  = "LDM", f = 1)


f1 <- rbindlist(list(resF1, sdmF1, emF1, ldmF1)) %>% mutate(point = 1:890)

ani1 <- f1 %>% rbind(allIndYears %>% dplyr::select(dists, absElev, class) %>%
                       mutate(f = 2, point = 1:890))

ani1$class <- factor(ani1$class, levels = c("SDM", "EM", "R", "LDM"))

a <-  ggplot(ani1) + geom_point(aes(dists, absElev, color = class, frame = f)) +
  theme_bw() + theme(legend.position = "none") +
  ylab("Abosulte elevation change (m)") +   xlab("Geographic distance (m)") +
  scale_color_brewer(palette = "Dark2")

ggplotly(a) %>%  animation_opts(frame = 1500, transition = 1500, redraw = FALSE) %>%
  add_text(x = c(c(3000, 100000),c(0,110000, 30000, 35000)),
           y = c(c(0, 1500),c(-200, 500, 1800, -200)), 
           yshift = 100,
           text = c(c("<b>Residents","<b>Migrants"), 
                    c("<b>Residents", "<b>Long \n distance \n migrants", 
                      "<b>Elevational migrants", "<b>Short distance \n migrants")),
           frame = c(c(1, 1), c(2, 2, 2, 2)),
           showlegend = FALSE,
           textfont = list(family = "century gothic", size = 20,
                           color = c("black", "black", "#7570b3", 
                                     "#e7298a", "#d95f02", "#1b9e77")))


```


Multiyear movements
```{r repair distance, echo=FALSE}
getY2Y <- function(id){
  t <- allIndYears %>% arrange(years) %>% filter(elk == id) %>%
    dplyr::select(elk, years, class, dists, elevs)
  year1 <- c()
  year2 <- c()
  strat1 <- c()
  strat2 <- c()
  sp1dist <- c()
  sp2dist <- c()
  sp1elev <- c()
  sp2elev <- c()
  
  for (i in 1:(nrow(t)-1)) {
    year1 <- c(year1, t$years[i])
    year2 <- c(year2, t$years[i+1])
    strat1 <- c(strat1, t$class[i])
    strat2 <- c(strat2, t$class[i+1])
    sp1dist <- c(sp1dist, t$dists[i])
    sp2dist <- c(sp2dist, t$dists[i+1])
    sp1elev <- c(sp1elev, t$elevs[i])
    sp2elev <- c(sp2elev, t$elevs[i+1])
    

  }
  return(data.table(id, year1, year2, strat1, strat2, sp1dist, sp2dist, sp1elev, sp2elev))
}

y2y <- map_dfr(unique(allIndYears$elk), getY2Y)

y2y$switch <- y2y$strat1 != y2y$strat2

y2y$switchID <- paste0(y2y$id, "_", y2y$year1, "-", y2y$year2)

y2y <- y2y %>% mutate(elevDiff = sp2elev - sp1elev, distanceDiff = sp2dist - sp1dist,
               vecDiff =sqrt(elevDiff^2 + distanceDiff^2))

#adding herd and year
gps <- fread("../Switching3/movementData/multiburstsNC.csv") %>% distinct(elkYear, startDateYear, herd)

y2y$elkYear <- paste(y2y$id, y2y$year1, sep = "_")

y2y <- y2y %>% merge(gps) %>% mutate(years = paste0(startDateYear+1, "-", startDateYear + 2)) %>%
  dplyr::select(elk = id, switchID, herd, years, year1, year2, strat1, strat2, switch, sp1dist, sp2dist,
                sp1elev, sp2elev, distanceDiff, elevDiff, vecDiff)

fwrite(y2y, "movementData/updatedSwitchTable.csv")


```





```{r covariates, echo = F}
#removed sand creek

y2y <- y2y %>% filter(herd != "Sand Creek")

#winter range 2 crop prop
crop <- fread("../Switching3/covariates/crop/cropProp.csv") %>% filter(p == "winter2") %>%
  rename(switchID = id) %>% dplyr::select(-p, -year)

y2y <- y2y %>% merge(crop)

#winter range 2 and migratory period dev prop
dev <- fread("../Switching3/covariates/development/devProp.csv")

winter2dev <- dev %>% filter(p == "winter2") %>% dplyr::select(-year, -p) %>%
  rename(switchID = id)
colnames(winter2dev)[2] <- paste0("winter2", colnames(winter2dev)[2])

springMigDev <- dev %>% filter(p == "springMig") %>% dplyr::select(-year, -p) %>%
  rename(switchID = id)
colnames(springMigDev)[2] <- paste0("springMig", colnames(springMigDev)[2])

y2y <- y2y %>% merge(winter2dev) %>% merge(springMigDev)

#feed ground
feed <- fread("../Switching3/covariates/feed/feedAccess.csv")

winter2feed <- feed %>% filter(p == "winter2") %>% dplyr::select(-numFeedgrounds, -p) %>%
  rename(switchID = id)
colnames(winter2feed)[2] <- paste0("winter2", colnames(winter2feed)[2])

y2y <- y2y %>% merge(winter2feed)

#spring green up
greenUp <- fread("../Switching3/covariates/greenUp/irg.csv")

springMigGreenUp <- greenUp %>% filter(period == "springMig") %>%
  dplyr::select(switchID, meanDFP, -period)

y2y <- y2y %>% merge(springMigGreenUp)

#max snow depth

snow <- fread("../Switching3/covariates/snow/snodasExtraction.csv") %>% group_by(switchID, period) %>%
  dplyr::summarise(meanSnow = mean(Snow_Depth_mean, na.rm = T),
                   varSnow = var(Snow_Depth_mean, na.rm = T),
                   maxSnow = max(Snow_Depth_mean, na.rm = T)) %>%
  filter(period == "winter2") %>% dplyr::select(switchID, maxSnow)

y2y <- y2y %>% merge(snow)

#add herd diversity
shannonHdiversity <- function(h){
  herdTable <- allIndYears %>% filter(elk %in% y2y$elk) %>% merge(
    y2y %>% dplyr::select(elk, herd)
  ) %>% filter(herd == h) 
  
  props <- as.numeric(table(herdTable$class) / sum(table(herdTable$class)))
  hSum <- 0
  for(i in 1:length(props)) {
    hSum <- hSum + props[i]*log(props[i])
  }
  
  return(data.table(herd = h, diversity = -1*hSum))
}

#max value is 1.386294, where each of the 4 strategies has the same number of individuals
hd <- map_dfr(unique(y2y$herd), shannonHdiversity)

y2y <- y2y %>% merge(hd, by = "herd") %>% dplyr::select(switchID, elk, herd, everything())

```

``` {r basic movement tactic results, echo = F, eval = F}
#do I want to redo classifcation with only used individuals? 7 elk years off
y2yResults <- y2y %>% mutate(elkYear1 = paste(elk, year1, sep = "_"), elkYear2 = paste(elk, year2, sep = "_"))

usedIndYears <- allIndYears %>% filter(elkYear %in% y2yResults$elkYear1 | 
                                     elkYear %in% y2yResults$elkYear2)

yearlyDist <- strategyByYear <- usedIndYears %>% merge(gps) %>%
  mutate(actualYear = startDateYear + 1) %>%
  group_by(actualYear, class) %>% summarise(n = n()) %>% merge(
    usedIndYears %>% merge(gps) %>% mutate(actualYear = startDateYear + 1) %>%
       group_by(actualYear) %>% summarise(total = n())
  ) %>% mutate(prop = n / total)

ggplot(yearlyDist) + geom_point(aes(actualYear, prop, color = class)) + 
  geom_line(aes(actualYear, prop, color = class)) +
  scale_x_continuous(breaks = unique(yearlyDist$actualYear))

annualSwitching <- y2y %>% group_by(strat1, years) %>% summarise(sr = sum(as.numeric(switch))/n())
sd(filter(annualSwitching, strat1 == "SDM")$sr)

yearlyBalance <- y2y %>% filter(switch == T) %>% group_by(years, strat1, strat2) %>% summarise(n = n()) %>% 
  mutate(type = paste(strat1, strat2, sep = " - ")) %>% ungroup() %>% dplyr::select(-strat2, -strat1)%>%
  pivot_wider(names_from = type, values_from = n) 

yearlyBalance[is.na(yearlyBalance)] <- 0

yearlyBalance$totalSwitches <-rowSums(yearlyBalance[, 2:12 ])

fwrite(yearlyBalance, "balancing.csv")

```


``` {r basic movement tactic lines for map, echo = F, eval = F}
y2yResults <- y2y %>% mutate(elkYear1 = paste(elk, year1, sep = "_"), elkYear2 = paste(elk, year2, sep = "_"))

#only one year per ind on map
usedIndYears <- allIndYears %>% filter(elkYear %in% y2yResults$elkYear1 | 
                                     elkYear %in% y2yResults$elkYear2)  %>% distinct(elk, .keep_all = T)

residents <- usedIndYears %>% filter(class == "R") %>% dplyr::select(elkYear, class)
em <- usedIndYears %>% filter(class == "EM") %>% sample_n(22) %>% dplyr::select(elkYear, class)
sdm <- usedIndYears %>% filter(class == "SDM") %>% sample_n(22) %>% dplyr::select(elkYear, class)
ldm <- usedIndYears %>% filter(class == "LDM") %>% sample_n(22) %>% dplyr::select(elkYear, class)

indsForMap <- rbindlist(list(residents, em, sdm, ldm))
library(sf)

lines <- fread("../Switching3/movementData/multiburstsNC.csv") %>% filter(elkYear %in% indsForMap$elkYear) %>%
  merge(indsForMap) %>% arrange(acquisition_time) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>% group_by(elkYear, class) %>%
  summarise(do_union = F) %>% st_cast("LINESTRING")

st_write(lines, "mapFigs/data", "lines", driver = "ESRI Shapefile", append = F)


```

``` {r alluvial, echo = F, eval = F}
forAlluv <- y2y %>% group_by(strat1, strat2) %>% dplyr::summarise(n = n()) %>% filter(strat1 != strat2)

#all = 105/478 = 22%
#EM: 41/108=38%
#R: 6/23=26%
#LDM: 11/86=13%
#SDM: 41/256=16%

ggplot(forAlluv,
       aes(y = n, axis1 = strat1, axis2 = strat2)) +
  geom_alluvium(aes(fill = strat1), width = 1/12) +
  geom_stratum(width = 1/12, fill = "black", color = "grey") +
  geom_label(stat = "stratum", 
             aes(label = after_stat(paste0(stratum, ": ", c(41, 6, 17, 41, 45, 6, 21, 33) ))), 
             family = "Century Gothic") +
  theme_bw() + ylab("") + xlab("") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.ticks = element_blank(), axis.text = element_blank(),
        panel.border = element_blank(), text=element_text(family = "Century Gothic")) + 
  labs(fill = "Strategy") +
  scale_fill_manual(values = c("#1b9e77", "#d95f02", "#7570b3", "#e7298a"))

```


``` {r vifTesting, echo = FALSE, eval = FALSE}
#all two-way combinations of variables pass VIF threshold test

vars <- colnames(y2y)[17:23]

#all two way combinations of variables
combos <- combn(vars, 2) %>% t() %>% as.data.table()


#testing to see if the particular var combination does not violate
#VIF threshold of 2, (Zuur, Ieno, & Elphick, 2010)


#for positive==
vifTest <- function(comboNum) {
  
  vifs <- vif(y2y %>% filter(strat1 == "LDM") %>% dplyr::select(combos[comboNum,] %>% as.character()))
  
  if(!is.na(all(vifs$VIF<2)) &  all(vifs$VIF<2) == T){
    data.table(vars = list(combos[comboNum,] %>% as.character()), passVIF = T) %>% return()
  } else {
    data.table(vars = list(combos[comboNum,] %>% as.character()), passVIF = F) %>% return()
  }
}

map_dfr(1:21, vifTest)

```



```{r model glm AIC just resident, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 

#competitive, yikes!
null <- glm(switch ~ 1, data = y2y %>% filter(strat1 == "R"), family = "binomial")

y2y$switch <- as.factor(y2y$switch)

#one variable models with strategy interaction
model1 <- train(switch ~ propCrop, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale')) 

model2 <- train(switch ~ winter2propDev, data = y2y %>% filter(strat1 == "R"), method = "glm", family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model3 <- train(switch ~ springMigpropDev,data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model4 <- train(switch ~ winter2feedAccess,data = y2y %>% filter(strat1 == "R"),method = "glm",
                        family = "binomial",trControl = fitControl,preProcess = c('center', 'scale'))

model5 <- train(switch ~ meanDFP,data = y2y %>% filter(strat1 == "R"), method = "glm",family = "binomial",
                trControl = fitControl,preProcess = c('center', 'scale'))

model6 <- train(switch ~ maxSnow,data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl,preProcess = c('center', 'scale'))

model7 <- train(switch ~ diversity,data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model8 <- train(switch ~ propCrop*springMigpropDev, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model9 <- train(switch ~ propCrop*winter2feedAccess, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model10 <- train(switch ~ propCrop*meanDFP, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model11 <- train(switch ~ propCrop*maxSnow, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model12 <- train(switch ~ propCrop*diversity, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model13 <- train(switch ~ winter2propDev*springMigpropDev, data = y2y %>% filter(strat1 == "R"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model14 <- train(switch ~ winter2propDev*winter2feedAccess, data = y2y %>% filter(strat1 == "R"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))


model15 <- train(switch ~ winter2propDev*meanDFP, data = y2y %>% filter(strat1 == "R"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))

model16 <- train(switch ~ winter2propDev*maxSnow, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model17 <- train(switch ~ winter2propDev*diversity, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model18 <- train(switch ~ springMigpropDev*winter2feedAccess, data = y2y %>% filter(strat1 == "R"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model19 <- train(switch ~ springMigpropDev*meanDFP, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model20 <- train(switch ~ springMigpropDev*maxSnow, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model21 <- train(switch ~ springMigpropDev*diversity, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model22 <- train(switch ~ winter2feedAccess*meanDFP, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model23 <- train(switch ~ winter2feedAccess*maxSnow, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model24 <- train(switch ~ winter2feedAccess*diversity, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


model25 <- train(switch ~ meanDFP*maxSnow, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model26 <- train(switch ~ meanDFP*diversity, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model27 <- train(switch ~ maxSnow*diversity, data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#models 2, 5, 6, 7, 24, 27: no 95% sig covs; 1 sig cov at 85% (model 5), as well as null model
AICcmodavg::aictab(list(model1$finalModel, model2$finalModel, model3$finalModel, model4$finalModel,
                        model5$finalModel, model6$finalModel, model7$finalModel, model8$finalModel, 
                        model9$finalModel, model10$finalModel, model11$finalModel, model12$finalModel, 
                        model13$finalModel, model14$finalModel, model15$finalModel, model16$finalModel,
                        model17$finalModel, model18$finalModel, model19$finalModel, model20$finalModel,
                        model21$finalModel, model22$finalModel, model23$finalModel, model24$finalModel,
                        model25$finalModel, model26$finalModel, model27$finalModel))

```


```{r visualizing informative covs for residents, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 


y2y$switch <- as.factor(y2y$switch)

model5 <- train(switch ~ meanDFP,data = y2y %>% filter(strat1 == "R"), method = "glm",family = "binomial",
                trControl = fitControl,preProcess = c('center', 'scale'))

yardstick::mcc_vec(as.factor(model5$trainingData$.outcome), predict(model5, model5$trainingData))


coef <- confint(model5$finalModel, level = .85) %>% as.data.frame() %>% 
  mutate(sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))

preproc <- preProcess(y2y %>% filter(strat1 == "R") %>% dplyr::select(meanDFP),
                      method = c("center", "scale"))

#meanDFP
newdata1 <- with(data = model5$trainingData, 
                 data.frame(meanDFP = seq(min(filter(y2y, strat1 == "R")$meanDFP),
                                          max(filter(y2y, strat1 == "R")$meanDFP), by = 1)))

newdata2 <- predict(preproc, newdata1)

p <- predict(model5$finalModel, newdata = newdata2,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata1$pred <- p$fit
newdata1$ll <- p$fit - 1.44 * p$se.fit
newdata1$ul <- p$fit + 1.44 * p$se.fit

newdata1 <- newdata1 %>%  mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))


meanDFP <- ggplot(newdata1) + 
  geom_line(aes(x = meanDFP, y = pred), alpha = .8) +
  geom_ribbon(aes(x = meanDFP, y = pred, ymin = ll,ymax = ul), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Mean DFP during herd-level migratory period") + 
  theme_bw() + theme(legend.title = element_blank()) +
  geom_rug(data = y2y %>% filter(strat1 == "R"), aes(meanDFP)) +
  scale_x_continuous(breaks = seq(0, 80, 10)) +
  scale_y_continuous(breaks = seq(0, 1, .1)) + ylim(0, 1)


##########################

model6 <- train(switch ~ maxSnow,data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl,preProcess = c('center', 'scale'))

mltools::mcc(predict(model6, model6$trainingData), model6$trainingData$.outcome)


coef <- confint(model6$finalModel, level = .85) %>% as.data.frame() %>% 
  mutate(sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))

preproc <- preProcess(y2y %>% filter(strat1 == "R") %>% dplyr::select(maxSnow),
                      method = c("center", "scale"))

#snow
newdata1 <- with(data = model5$trainingData, 
                 data.frame(maxSnow = seq(min(filter(y2y, strat1 == "R")$maxSnow),
                                          max(filter(y2y, strat1 == "R")$maxSnow), by = .01)))

newdata2 <- predict(preproc, newdata1)

p <- predict(model6$finalModel, newdata = newdata2,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata1$pred <- p$fit
newdata1$ll <- p$fit - 1.44 * p$se.fit
newdata1$ul <- p$fit + 1.44 * p$se.fit

newdata1 <- newdata1 %>%  mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))


maxSnow <- ggplot(newdata1) + 
  geom_line(aes(x = maxSnow, y = pred), alpha = .8) +
  geom_ribbon(aes(x = maxSnow, y = pred, ymin = ll,ymax = ul), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Maximum snow depth in winter range (m)") + 
  theme_bw() + theme(legend.title = element_blank()) +
  geom_rug(data = y2y %>% filter(strat1 == "R"), aes(maxSnow)) +
  scale_x_continuous(breaks = seq(0, 4, .5)) +
  scale_y_continuous(breaks = seq(0, 1, .2)) + ylim(0, 1)


##########################

model7 <- train(switch ~ diversity,data = y2y %>% filter(strat1 == "R"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

mltools::mcc(predict(model7, model7$trainingData), model7$trainingData$.outcome)


coef <- confint(model7$finalModel, level = .85) %>% as.data.frame() %>% 
  mutate(sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))

preproc <- preProcess(y2y %>% filter(strat1 == "R") %>% dplyr::select(diversity),
                      method = c("center", "scale"))

#diversity
newdata1 <- with(data = model5$trainingData, 
                 data.frame(diversity = seq(min(filter(y2y, strat1 == "R")$diversity),
                                          max(filter(y2y, strat1 == "R")$diversity), by = 0.01)))

newdata2 <- predict(preproc, newdata1)

p <- predict(model7$finalModel, newdata = newdata2,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata1$pred <- p$fit
newdata1$ll <- p$fit - 1.44 * p$se.fit
newdata1$ul <- p$fit + 1.44 * p$se.fit

newdata1 <- newdata1 %>%  mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))


diversity <- ggplot(newdata1) + 
  geom_line(aes(x = diversity, y = pred), alpha = .8) +
  geom_ribbon(aes(x = diversity, y = pred, ymin = ll,ymax = ul), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Herd-level diversity") + 
  theme_bw() + theme(legend.title = element_blank()) +
  geom_rug(data = y2y %>% filter(strat1 == "R"), aes(diversity)) + ylim(0, 1)



ggpubr::ggarrange(meanDFP, maxSnow, diversity, labels = c("A.", "B.", "C."))

```


```{r model glm AIC just EM, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 

#competitive
null <- glm(switch ~ 1, data = y2y %>% filter(strat1 == "EM"), family = "binomial")

y2y$switch <- as.factor(y2y$switch)

#one variable models with strategy interaction
model1 <- train(switch ~ propCrop, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale')) 

model2 <- train(switch ~ winter2propDev, data = y2y %>% filter(strat1 == "EM"), method = "glm", family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model3 <- train(switch ~ springMigpropDev,data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model4 <- train(switch ~ winter2feedAccess,data = y2y %>% filter(strat1 == "EM"),method = "glm",
                        family = "binomial",trControl = fitControl,preProcess = c('center', 'scale'))

model5 <- train(switch ~ meanDFP,data = y2y %>% filter(strat1 == "EM"), method = "glm",family = "binomial",
                trControl = fitControl,preProcess = c('center', 'scale'))

model6 <- train(switch ~ maxSnow,data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl,preProcess = c('center', 'scale'))

model7 <- train(switch ~ diversity,data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model8 <- train(switch ~ propCrop*winter2propDev, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model9 <- train(switch ~ propCrop*springMigpropDev, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model10 <- train(switch ~ propCrop*winter2feedAccess, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model11 <- train(switch ~ propCrop*meanDFP, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model12 <- train(switch ~ propCrop*maxSnow, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model13 <- train(switch ~ propCrop*diversity, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model14 <- train(switch ~ winter2propDev*springMigpropDev, data = y2y %>% filter(strat1 == "EM"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model15 <- train(switch ~ winter2propDev*winter2feedAccess, data = y2y %>% filter(strat1 == "EM"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))


model16 <- train(switch ~ winter2propDev*meanDFP, data = y2y %>% filter(strat1 == "EM"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))

model17 <- train(switch ~ winter2propDev*maxSnow, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model18 <- train(switch ~ winter2propDev*diversity, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model19 <- train(switch ~ springMigpropDev*winter2feedAccess, data = y2y %>% filter(strat1 == "EM"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model20 <- train(switch ~ springMigpropDev*meanDFP, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model21 <- train(switch ~ springMigpropDev*maxSnow, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model22 <- train(switch ~ springMigpropDev*diversity, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model23 <- train(switch ~ winter2feedAccess*meanDFP, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model24 <- train(switch ~ winter2feedAccess*maxSnow, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model25 <- train(switch ~ winter2feedAccess*diversity, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


model26 <- train(switch ~ meanDFP*maxSnow, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model27 <- train(switch ~ meanDFP*diversity, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model28 <- train(switch ~ maxSnow*diversity, data = y2y %>% filter(strat1 == "EM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#models 2, 3, 4, 5, 18, as well as null 
AICcmodavg::aictab(list(model1$finalModel, model2$finalModel, model3$finalModel, model4$finalModel,
                        model5$finalModel, model6$finalModel, model7$finalModel, model8$finalModel, 
                        model9$finalModel, model10$finalModel, model11$finalModel, model12$finalModel, 
                        model13$finalModel, model14$finalModel, model15$finalModel, model16$finalModel,
                        model17$finalModel, model18$finalModel, model19$finalModel, model20$finalModel,
                        model21$finalModel, model22$finalModel, model23$finalModel, model24$finalModel,
                        model25$finalModel, model26$finalModel, model27$finalModel, model28$finalModel))

```

```{r visualizing informative covs for EM, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 

y2y$switch <- as.factor(y2y$switch)


model18 <- train(switch ~ winter2propDev*diversity, data = y2y %>% filter(strat1 == "EM"),
                 method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

yardstick::mcc_vec(as.factor(model18$trainingData$.outcome), predict(model18, model18$trainingData))


coef <- confint(model18$finalModel, level = .85) %>% as.data.frame() %>% 
  mutate(sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))

preproc <- preProcess(y2y %>% filter(strat1 == "EM") %>% dplyr::select(winter2propDev, diversity),
                      method = c("center", "scale"))

#winterDev
newdata1 <- with(data = model18$trainingData, 
                 data.frame(winter2propDev = seq(min(filter(y2y, strat1 == "EM")$winter2propDev),
                                          max(filter(y2y, strat1 == "EM")$winter2propDev), by = 0.001),
                                                         diversity = 0))

newdata2 <- predict(preproc, newdata1)

newdata2$diversity <- 0
newdata2$`winter2propDev:diversity` <- 0

p <- predict(model18$finalModel, newdata = newdata2,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata1$pred <- p$fit
newdata1$ll <- p$fit - 1.44 * p$se.fit
newdata1$ul <- p$fit + 1.44 * p$se.fit

newdata1 <- newdata1 %>% mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))

dev <- ggplot(newdata1) + 
  geom_line(aes(x = winter2propDev, y = pred), alpha = .8) +
  geom_ribbon(aes(x = winter2propDev, y = pred, ymin = ll,ymax = ul), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Proportion of winter range in developed land") + 
  theme_bw() + theme(legend.title = element_blank()) +
  geom_rug(data = y2y %>% filter(strat1 == "EM"), aes(winter2propDev)) + ylim(0, 1)


#winterDev without feed
newdata3 <- with(data = model18$trainingData, 
                 data.frame(winter2propDev = 0,
                            diversity = seq(min(filter(y2y, strat1 == "EM")$diversity),
                                          max(filter(y2y, strat1 == "EM")$diversity), by = 0.01)))

newdata4 <- predict(preproc, newdata3)

newdata4$winter2propDev <- 0
newdata4$`winter2propDev:diversity` <- 0

p <- predict(model18$finalModel, newdata = newdata4,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata3$pred <- p$fit
newdata3$ll <- p$fit - 1.44 * p$se.fit
newdata3$ul <- p$fit + 1.44 * p$se.fit

newdata3 <- newdata3 %>% mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))

div <- ggplot(newdata3) + 
  geom_line(aes(x = diversity, y = pred), alpha = .8) +
  geom_ribbon(aes(x = diversity, y = pred, ymin = ll,ymax = ul), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Herd-level diversity") + 
  theme_bw() + theme(legend.title = element_blank()) +
  geom_rug(data = y2y %>% filter(strat1 == "EM"), aes(diversity)) + ylim(0, 1)

#interaction
grid <- expand.grid(
  seq(min(filter(y2y, strat1 == "EM")$winter2propDev),
                                          max(filter(y2y, strat1 == "EM")$winter2propDev), by = 0.0001), seq(min(filter(y2y, strat1 == "EM")$diversity),
                                          max(filter(y2y, strat1 == "EM")$diversity), by = 0.001))


newdata5 <- with(data = model18$trainingData, data.frame(winter2propDev = grid$Var1,
                                                         diversity = grid$Var2))

newdata6 <- predict(preproc, newdata5)

newdata6$`winter2propDev:diversity` <- newdata6$winter2propDev*newdata6$diversity

p <- predict(model18$finalModel, newdata = newdata6,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata5$pred <- p$fit
newdata5$ll <- p$fit - 1.44 * p$se.fit
newdata5$ul <- p$fit + 1.44 * p$se.fit

newdata5 <- newdata5 %>% mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))


interaction <- ggplot(newdata5) + 
  geom_tile(aes(x = winter2propDev, y = diversity, fill = pred)) +
  theme_bw() + xlab("Proportion of winter range in developed land") +
  ylab("Herd-level diversity") +
  scale_fill_viridis_c(option = "B", direction = -1, name = "P(switch)", breaks = seq(.1, 1, by = .2)) +
  geom_rug(data = y2y %>% filter(strat1 == "EM"), aes(winter2propDev), sides = "b") +
  #this one not showing up
  geom_rug(data = y2y %>% filter(strat1 == "EM"), aes(y = diversity), sides = "l")

ggpubr::ggarrange(dev, div, interaction, labels = c("A.", "B.", "C."))

```


```{r model glm AIC just SDM, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 

#not competitive
null <- glm(switch ~ 1, data = y2y %>% filter(strat1 == "SDM"), family = "binomial")

y2y$switch <- as.factor(y2y$switch)

#one variable models with strategy interaction
model1 <- train(switch ~ propCrop, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale')) 

model2 <- train(switch ~ winter2propDev, data = y2y %>% filter(strat1 == "SDM"), method = "glm", family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model3 <- train(switch ~ springMigpropDev,data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model4 <- train(switch ~ winter2feedAccess,data = y2y %>% filter(strat1 == "SDM"),method = "glm",
                        family = "binomial",trControl = fitControl,preProcess = c('center', 'scale'))

model5 <- train(switch ~ meanDFP,data = y2y %>% filter(strat1 == "SDM"), method = "glm",family = "binomial",
                trControl = fitControl,preProcess = c('center', 'scale'))

model6 <- train(switch ~ maxSnow,data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl,preProcess = c('center', 'scale'))

model7 <- train(switch ~ diversity,data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model8 <- train(switch ~ propCrop*winter2propDev, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model9 <- train(switch ~ propCrop*springMigpropDev, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model10 <- train(switch ~ propCrop*winter2feedAccess, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model11 <- train(switch ~ propCrop*meanDFP, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model12 <- train(switch ~ propCrop*maxSnow, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model13 <- train(switch ~ propCrop*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model14 <- train(switch ~ winter2propDev*springMigpropDev, data = y2y %>% filter(strat1 == "SDM"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model15 <- train(switch ~ winter2propDev*winter2feedAccess, data = y2y %>% filter(strat1 == "SDM"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))


model16 <- train(switch ~ winter2propDev*meanDFP, data = y2y %>% filter(strat1 == "SDM"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))

model17 <- train(switch ~ winter2propDev*maxSnow, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model18 <- train(switch ~ winter2propDev*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model19 <- train(switch ~ springMigpropDev*winter2feedAccess, data = y2y %>% filter(strat1 == "SDM"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model20 <- train(switch ~ springMigpropDev*meanDFP, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model21 <- train(switch ~ springMigpropDev*maxSnow, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model22 <- train(switch ~ springMigpropDev*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model23 <- train(switch ~ winter2feedAccess*meanDFP, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model24 <- train(switch ~ winter2feedAccess*maxSnow, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model25 <- train(switch ~ winter2feedAccess*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


model26 <- train(switch ~ meanDFP*maxSnow, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model27 <- train(switch ~ meanDFP*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model28 <- train(switch ~ maxSnow*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#model 10, 22: 1 sig cov at 95% and 85%
AICcmodavg::aictab(list(model1$finalModel, model2$finalModel, model3$finalModel, model4$finalModel,
                        model5$finalModel, model6$finalModel, model7$finalModel, model8$finalModel, 
                        model9$finalModel, model10$finalModel, model11$finalModel, model12$finalModel, 
                        model13$finalModel, model14$finalModel, model15$finalModel, model16$finalModel,
                        model17$finalModel, model18$finalModel, model19$finalModel, model20$finalModel,
                        model21$finalModel, model22$finalModel, model23$finalModel, model24$finalModel,
                        model25$finalModel, model26$finalModel, model27$finalModel, model28$finalModel))

```


```{r testing SDM model, echo = F, eval = F}
ggplot(y2y %>% filter(strat1 == "SDM")) + geom_histogram(aes(propCrop, fill = switch)) +
  facet_grid(~winter2feedAccess)

y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0)) 
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)


d1 <- y2y %>% filter(strat1 == "SDM") %>% dplyr::select(switch, propCrop, winter2feedAccess)

model <- glm(switch ~ propCrop*winter2feedAccess, data = d1, family = binomial)

#propCrop with feed, all 4 switches by fed elk all had 0 propCrop in winter
newdata1 <- with(data = d1, data.frame(propCrop = seq(0, 1, by = 0.01),
                                                        winter2feedAccess = as.factor(1)))


newdata1$`propCrop:winter2feedAccess` <- newdata1$propCrop

p <- predict(model, newdata = newdata1,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata1$pred <- p$fit
newdata1$ll <- p$fit - 1.44 * p$se.fit
newdata1$ul <- p$fit + 1.44 * p$se.fit
newdata1$fed <- T

newdata2 <- with(data = d1, data.frame(propCrop = seq(0, 0.83, by = 0.01),
                                                        winter2feedAccess = as.factor(0)))


newdata2$`propCrop:winter2feedAccess` <- 0

p <- predict(model, newdata = newdata2,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata2$pred <- p$fit
newdata2$ll <- p$fit - 1.44 * p$se.fit
newdata2$ul <- p$fit + 1.44 * p$se.fit
newdata2$fed <- F

newdata <- rbind(newdata1, newdata2)

testPoints <- y2y %>% filter(strat1 == "SDM") %>% mutate(fed = ifelse(winter2feedAccess == 1, T, F))


interaction <- ggplot(newdata) + 
  #geom_jitter(data = testPoints, aes(propCrop, as.numeric(switch), color =fed), width = 0, height = 0.1) +
  geom_line(aes(x = propCrop, y = pred, color = fed), alpha = .8) +
  geom_ribbon(aes(x = propCrop, y = pred, ymin = ll,ymax = ul, fill = fed), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Proportion of winter range in croplands") + 
  theme_bw() + labs(fill = "Fed", color = "Fed") + scale_x_continuous(breaks = seq(0, 1, by = .2)) +
  geom_rug(data = y2y %>% filter(strat1 == "SDM")%>% 
             mutate(winter2feedAccess = ifelse(winter2feedAccess == 1, T, F)),
           aes(propCrop, color = winter2feedAccess)) + ylim(0, 1)

coef <- confint(model, level = .85) %>% as.data.frame() %>% 
  mutate(estimate = as.numeric(coef(model)),
         sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))
```


```{r visualizing informative covs for SDM, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0)) %>%
    mutate(switch = as.character(switch))

fitControl <- trainControl() 


# 
# #139_1-2 has cropProp =1
# #warning
model10 <- train(switch ~ propCrop*winter2feedAccess, data = y2y %>% filter(strat1 == "SDM"),
                 method = "glm",family = "binomial",
                 trControl = fitControl, preProcess = c('center', 'scale'))

yardstick::mcc_vec(as.factor(model10$trainingData$.outcome), predict(model10, model10$trainingData))
# 
# coef <- confint(model10$finalModel, level = .85) %>% as.data.frame() %>% 
#   mutate(estimate = as.numeric(coef(model10$finalModel)),
#          sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))
# 
# 
# 
# preproc <- preProcess(y2y %>% filter(strat1 == "SDM") %>% dplyr::select(propCrop, winter2feedAccess),
#                       method = c("center", "scale"))
# 
# 
# 
# #winter2 feed access, sig with access to feedground increasing switching likelihood
# 
# #propCrop with feed, all 4 switches by fed elk all had 0 propCrop in winter
# newdata1 <- with(data = model10$trainingData, data.frame(propCrop = seq(0, 1, by = 0.01),
#                                                         winter2feedAccess1 = 1))
# 
# newdata2 <- predict(preproc, newdata1)
# 
# newdata2$`propCrop:winter2feedAccess1` <- newdata2$propCrop
# 
# p <- predict(model10$finalModel, newdata = newdata2,
#              interval="confidence",se.fit = T, level = 0.85, type = "response")
# 
# newdata1$pred <- p$fit
# newdata1$ll <- p$fit - 1.44 * p$se.fit
# newdata1$ul <- p$fit + 1.44 * p$se.fit
# newdata1$fed <- T
# 
# #propCrop without feed
# newdata3 <- with(data = model10$trainingData, data.frame(propCrop = seq(0, 0.83, by = 0.01),
#                                                         winter2feedAccess1 = 0))
# 
# newdata4 <- predict(preproc, newdata3)
# newdata4$`propCrop:winter2feedAccess1` <- 0
# 
# p <- predict(model10$finalModel, newdata = newdata4,
#              interval="confidence",se.fit = T, level = 0.85, type = "response")
# 
# #predicts that no unfed SDM will switch, but of 41 SDM switches 37 are unfed
# newdata3$pred <- p$fit
# newdata3$ll <- p$fit - 1.44 * p$se.fit
# newdata3$ul <- p$fit + 1.44 * p$se.fit
# newdata3$fed <- F
# 
# 
# 
# newdata <- rbindlist(list(newdata1, newdata3), fill = T) %>%
#   mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))
# 
# testPoints <- y2y %>% filter(strat1 == "SDM") %>% mutate(fed = ifelse(winter2feedAccess == 1, T, F))
# 
# #unfed switches at low crop prop not picked up by model
# ggplot(newdata) + 
#   #geom_jitter(data = testPoints, aes(propCrop, as.numeric(switch), color =fed), width = 0, height = 0.1) +
#   geom_line(aes(x = propCrop, y = pred, color = fed), alpha = .8) +
#   geom_ribbon(aes(x = propCrop, y = pred, ymin = ll,ymax = ul, fill = fed), alpha = 0.2) +
#   ylab("Probability of switching") + 
#   xlab("Proportion of winter range in croplands") + 
#   theme_bw() + labs(fill = "Fed", color = "Fed") + scale_x_continuous(breaks = seq(0, 1, by = .1)) +
#   geom_rug(data = y2y %>% filter(strat1 == "SDM") %>% 
#              mutate(winter2feedAccess = ifelse(winter2feedAccess == 1, T, F)),
#            aes(propCrop, color = winter2feedAccess)) 


#diversity from model22, but not on its own?
model22 <- train(switch ~ springMigpropDev*diversity, data = y2y %>% filter(strat1 == "SDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

yardstick::mcc_vec(as.factor(model22$trainingData$.outcome), predict(model22, model22$trainingData))


coef <- confint(model22$finalModel, level = .85) %>% as.data.frame() %>% 
  mutate(sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))

preproc <- preProcess(y2y %>% filter(strat1 == "SDM") %>% dplyr::select(springMigpropDev, diversity),
                      method = c("center", "scale"))

newdata5 <- with(data = model22$trainingData, data.frame(springMigpropDev = 0,
                                                        diversity = seq(0, 1.322088, by = 0.01)))

newdata6 <- predict(preproc, newdata5)
newdata6$springMigpropDev <- 0
newdata6$`springMigpropDev:diversity` <- 0

p <- predict(model22$finalModel, newdata = newdata6,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata5$pred <- p$fit
newdata5$ll <- p$fit - 1.44 * p$se.fit
newdata5$ul <- p$fit + 1.44 * p$se.fit

newdata5 <- newdata5 %>% mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul))

div <- ggplot(newdata5) + 
  geom_line(aes(x = diversity, y = pred), alpha = .8) +
  geom_ribbon(aes(x = diversity, y = pred, ymin = ll,ymax = ul), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Herd-level diversity") + 
  theme_bw() + theme(legend.title = element_blank()) +
  geom_rug(data = y2y %>% filter(strat1 == "SDM"), aes(diversity)) + ylim(0, 1)

ggpubr::ggarrange(interaction, div, labels = c("A.", "B."))

```


```{r model glm AIC just LDM, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 

#not competitive
null <- glm(switch ~ 1, data = y2y %>% filter(strat1 == "LDM"), family = "binomial")

y2y$switch <- as.factor(y2y$switch)

#one variable models with strategy interaction
model1 <- train(switch ~ propCrop, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale')) 

model2 <- train(switch ~ winter2propDev, data = y2y %>% filter(strat1 == "LDM"), method = "glm", family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model3 <- train(switch ~ springMigpropDev,data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model4 <- train(switch ~ winter2feedAccess,data = y2y %>% filter(strat1 == "LDM"),method = "glm",
                        family = "binomial",trControl = fitControl,preProcess = c('center', 'scale'))

model5 <- train(switch ~ meanDFP,data = y2y %>% filter(strat1 == "LDM"), method = "glm",family = "binomial",
                trControl = fitControl,preProcess = c('center', 'scale'))

model6 <- train(switch ~ maxSnow,data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl,preProcess = c('center', 'scale'))

model7 <- train(switch ~ diversity,data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model8 <- train(switch ~ propCrop*winter2propDev, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model9 <- train(switch ~ propCrop*springMigpropDev, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model10 <- train(switch ~ propCrop*winter2feedAccess, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model11 <- train(switch ~ propCrop*meanDFP, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model12 <- train(switch ~ propCrop*maxSnow, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model13 <- train(switch ~ propCrop*diversity, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model14 <- train(switch ~ winter2propDev*springMigpropDev, data = y2y %>% filter(strat1 == "LDM"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model15 <- train(switch ~ winter2propDev*winter2feedAccess, data = y2y %>% filter(strat1 == "LDM"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))


model16 <- train(switch ~ winter2propDev*meanDFP, data = y2y %>% filter(strat1 == "LDM"),method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))

model17 <- train(switch ~ winter2propDev*maxSnow, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model18 <- train(switch ~ winter2propDev*diversity, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model19 <- train(switch ~ springMigpropDev*winter2feedAccess, data = y2y %>% filter(strat1 == "LDM"),method = "glm",
                 family = "binomial",trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model20 <- train(switch ~ springMigpropDev*meanDFP, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model21 <- train(switch ~ springMigpropDev*maxSnow, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

#warning
model22 <- train(switch ~ springMigpropDev*diversity, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#warning
model23 <- train(switch ~ winter2feedAccess*meanDFP, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model24 <- train(switch ~ winter2feedAccess*maxSnow, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))
#warning
model25 <- train(switch ~ winter2feedAccess*diversity, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


model26 <- train(switch ~ meanDFP*maxSnow, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model27 <- train(switch ~ meanDFP*diversity, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))

model28 <- train(switch ~ maxSnow*diversity, data = y2y %>% filter(strat1 == "LDM"),method = "glm",family = "binomial",
                        trControl = fitControl, preProcess = c('center', 'scale'))


#model 14: all 3 sig cov
AICcmodavg::aictab(list(model1$finalModel, model2$finalModel, model3$finalModel, model4$finalModel,
                        model5$finalModel, model6$finalModel, model7$finalModel, model8$finalModel, 
                        model9$finalModel, model10$finalModel, model11$finalModel, model12$finalModel, 
                        model13$finalModel, model14$finalModel, model15$finalModel, model16$finalModel,
                        model17$finalModel, model18$finalModel, model19$finalModel, model20$finalModel,
                        model21$finalModel, model22$finalModel, model23$finalModel, model24$finalModel,
                        model25$finalModel, model26$finalModel, model27$finalModel, model28$finalModel))

```


```{r visualizing informative covs for LDM, echo = F, eval = F}
y2y$winter2feedAccess <- as.character(y2y$winter2feedAccess)
y2y$winter2feedAccess <- as.factor(y2y$winter2feedAccess)
y2y$winter2feedAccess <- relevel(y2y$winter2feedAccess, "0")
y2y <- y2y %>% mutate(switch = ifelse(switch == T, 1, 0))

fitControl <- trainControl() 


y2y$switch <- as.factor(y2y$switch)


#warning
model14 <- train(switch ~ winter2propDev*springMigpropDev, data = y2y %>% filter(strat1 == "LDM"),
                 method = "glm",
                 family = "binomial", trControl = fitControl, preProcess = c('center', 'scale'))

yardstick::mcc_vec(model14$trainingData$.outcome, predict(model14, model14$trainingData))


coef <- confint(model14$finalModel, level = .85) %>% as.data.frame() %>% 
  mutate(sig = ifelse((`7.5 %` < 0 & `92.5 %` < 0) | (`7.5 %` > 0 & `92.5 %` > 0), T, F))

preproc <- preProcess(y2y %>% filter(strat1 == "LDM") %>% dplyr::select(winter2propDev, springMigpropDev),
                      method = c("center", "scale"))

#winter2propDev
newdata1 <- with(data = model14$trainingData, data.frame(winter2propDev = seq(0, 0.041, by = 0.0001),
                                                         springMigpropDev = 0))

newdata2 <- predict(preproc, newdata1)

newdata2$springMigpropDev <- 0
newdata2$`winter2propDev:springMigpropDev` <- 0


p <- predict(model14$finalModel, newdata = newdata2,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata1$pred <- p$fit
newdata1$ll <- p$fit - 1.44 * p$se.fit
newdata1$ul <- p$fit + 1.44 * p$se.fit
newdata1$season <- "W.R."

#springMigpropDev
newdata3 <- with(data = model14$trainingData, data.frame(springMigpropDev = seq(0, 0.033, by = 0.0001),
                                                         winter2propDev = 0))

newdata4 <- predict(preproc, newdata3)

newdata4$winter2propDev <- 0
newdata4$`winter2propDev:springMigpropDev` <- 0

p <- predict(model14$finalModel, newdata = newdata4,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata3$pred <- p$fit
newdata3$ll <- p$fit - 1.44 * p$se.fit
newdata3$ul <- p$fit + 1.44 * p$se.fit
newdata3$season <- "Sp. mig."



newdata <- rbindlist(list(newdata1, newdata3), fill = T) %>%
  mutate(ll = ifelse(ll < 0, 0, ll), ul = ifelse(ul > 1, 1, ul), pred = ifelse(pred > 1, 1, pred))

forRug <- y2y %>% filter(strat1 == "LDM") %>% dplyr::select(dev = springMigpropDev) %>% mutate(season = "Sp. mig.") %>%
  rbind(
    y2y %>% filter(strat1 == "LDM") %>% dplyr::select(dev = winter2propDev) %>% mutate(season = "W.R.")
  )


#weird spike at 1
dev <- ggplot(newdata) + 
  geom_line(aes(x = winter2propDev, y = pred, color = season), alpha = .8) +
  geom_ribbon(aes(x = winter2propDev, y = pred, ymin = ll, ymax = ul, fill = season), alpha = 0.2) +
  geom_line(aes(x = springMigpropDev, y = pred, color = season), alpha = .8) +
  geom_ribbon(aes(x = springMigpropDev, y = pred, ymin = ll,ymax = ul, fill = season), alpha = 0.2) +
  ylab("Probability of switching") + 
  xlab("Proportion of developed lands") + 
  theme_bw() + theme(legend.title = element_blank()) + 
  geom_rug(data = forRug, aes(dev, color = season)) + xlim(0.000001, 0.041)



#springMigpropDev:winter2propDev
grid <- expand.grid(seq(0, 0.041, by = 0.0001), seq(0, 0.033, by = 0.0001))


newdata5 <- with(data = model14$trainingData, data.frame(springMigpropDev = grid$Var2,
                                                         winter2propDev = grid$Var1))

newdata6 <- predict(preproc, newdata5)

newdata6$`winter2propDev:springMigpropDev` <- newdata6$winter2propDev*newdata6$springMigpropDev

p <- predict(model14$finalModel, newdata = newdata6,
             interval="confidence",se.fit = T, level = 0.85, type = "response")

newdata5$pred <- p$fit
newdata5$ll <- p$fit - 1.44 * p$se.fit
newdata5$ul <- p$fit + 1.44 * p$se.fit


interaction <- ggplot(newdata5) + 
  geom_tile(aes(x = winter2propDev, y = springMigpropDev, fill = pred)) +
  theme_bw() + xlab("Proportion of winter range in developed land") +
  ylab("Proportion of spring migratory period in developed land") +
  scale_fill_viridis_c(option = "B", direction = -1, name = "P(switch)", breaks = seq(.1, 1, by = .2)) +
  geom_rug(data = y2y %>% filter(strat1 == "LDM"), aes(winter2propDev), sides = "b") +
  #this one not showing up
  geom_rug(data = y2y %>% filter(strat1 == "LDM"), aes(y = springMigpropDev), sides = "l")





ggpubr::ggarrange(dev, interaction, labels = c("A.", "B."))


```



